import argparse
import csv
import threading

class Mutant_result:
    def __init__(self):
        self.survived = 0
        self.no_coverage = 0
        self.killed = 0
    
    def get_survived(self):
        return self.survived
    def get_nocoverage(self):
        return self.no_coverage
    def get_killed(self):
        return self.killed
    
    def add_survived(self):
        self.survived += 1
    def add_nocoverage(self):
        self.no_coverage += 1
    def add_killed(self):
        self.killed += 1

    def add_result(self, mutant_result):
        if("SURVIVED" == mutant_result):
            self.add_survived()
        if("NO_COVERAGE" == mutant_result):
            self.add_nocoverage()
        if("KILLED" == mutant_result):
            self.add_killed()

mutants_histogram = {}

def get_first_key(subject, budget, stopping_condition, mutant):
    return "{} {} {} {}".format(subject, budget, stopping_condition, mutant)

def get_second_key(criterion):
    return "{}".format(criterion)

def count_mutant(subject, criterion, budget, stopping_condition, mutant, result):
    lock.acquire()
    try:
        global mutants_histogram
        first_key = get_first_key(subject, budget, stopping_condition, mutant)
        second_key = get_second_key(criterion)
        value = {} # {criterio:mutant_result}
        mutant_result = Mutant_result()
        if first_key in mutants_histogram:
            value = mutants_histogram[first_key]
            if second_key in value:
                mutant_result = value[second_key]
        
        mutant_result.add_result(result)
        value.update({second_key:mutant_result})
        mutants_histogram.update({first_key:value})
    except:
            print("ERROR! Adding mutant {}".format(first_key))
    finally:
        lock.release()

def pit_mutants_histogram(criterion, budget, stopping_condition, mutations_csv_path):
    #file = csv.DictReader(open(mutations_csv_path), newline='', )
    with open(mutations_csv_path, newline='') as csvfile:
        reader = csv.DictReader(csvfile, fieldnames=['NAME','SUBJECT','MUTANT_NAME','METHOD','LINE','RESULT','TEST'])
        keys_by_file = set()
        for row in reader:
            subject = row["SUBJECT"]
            mutant_key = row["MUTANT_NAME"]+"_"+row["METHOD"]+"_"+row["LINE"]
            result = row["RESULT"]
            if mutant_key in keys_by_file:
                mutant_key = mutant_key + "_2"
            count_mutant(subject, criterion, budget, stopping_condition, mutant_key, result)
            keys_by_file.add(mutant_key)

lock = threading.Lock()
headers_list = ["SUBJECT","BUDGET","STOP_COND","MUTANT_METHOD_LINE"]
def get_histogram():
    def add_header(name):
        global headers_list
        if name not in headers_list:
            headers_list.append(name)

    global mutants_histogram
    data = ""
    for key in mutants_histogram.keys():
        key_value = key.split(" ")
        subject = key_value[0]
        budget = key_value[1]
        stopping_condition = key_value[2]
        mutant = key_value[3]
        data += "{},{},{},{}".format(subject, budget, stopping_condition, mutant)
        value = mutants_histogram[key]
        for sec_key in value.keys():
            criterion = sec_key
            sec_value = value[sec_key]
            survived = sec_value.get_survived()
            no_coverage = sec_value.get_nocoverage()
            killed = sec_value.get_killed()
            alive = survived + no_coverage
            add_header("SURVIVED_{}".format(criterion))
            add_header("NO_COVERAGE_{}".format(criterion))
            add_header("KILLED_{}".format(criterion))
            add_header("ALIVE_{}".format(criterion))
            data += ",{},{},{},{}".format(survived, no_coverage, killed, alive)
        data += "\n"
    headers = ""
    add_colon = False
    for header in headers_list:
        if add_colon:
            headers += ","
        else:
            add_colon = True
        headers += header
    return headers + "\n" + data

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("mutations_csv", help="mutations.csv file generated by pit")
    args = parser.parse_args()
    pit_mutants_histogram("epaadjacentedges", "600", "maxtime", args.mutations_csv)
    print(get_histogram())
    print("Done!")